website/models.py
from datetime import datetime
from flask_login import UserMixin
from . import db


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    uuid = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    first_name = db.Column(db.String(1000))
    last_name = db.Column(db.String(1000))
    phone_nr = db.Column(db.String(1000))
    role = db.Column(db.String(16), nullable=False, default='user')
    created_at = db.Column(db.Date(), nullable=False, default=datetime.now())
    updated_at = db.Column(db.Date(), nullable=True)
    deleted_at = db.Column(db.Date(), nullable=True)

    def get_id(self):
        return (self.uuid)

website/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, BooleanField, FloatField, RadioField,
                     TextAreaField, SubmitField, DateField, EmailField, PasswordField,)
from wtforms.validators import DataRequired, Email, Length, ValidationError


class contact_form(FlaskForm):
    full_name = StringField("Voornaam", validators=[
        DataRequired(), Length(2, 1000)])

    email = EmailField(
        "E-mail", validators=[DataRequired(), Email(), Length(3, 50)])
    phone_nr = StringField("Telefoon", validators=[
                           DataRequired(), Length(0, 16)])
    submit = SubmitField("verzend!")

    def validate_phone_nr(form, field):
        if not field.data.isdigit():
            raise ValidationError("is niet een nummer")

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = 'database.db'


def create_app():
    """ initialises the website"""

    app = Flask(__name__, template_folder='templates')

    login_manager = LoginManager()
    login_manager.init_app(app)

    # WHEN IN PRODUCTION NEVER SHARE THIS KEY AND CHANGE IT TO SOMETHING THAT MAKES MORE SENSE LIKE A HASH
    app.config['SECRET_KEY'] = 'ThisIsSecret'
    app.config['SQLALCHEMY_DATABASE_URI'] = f"sqlite:///{DB_NAME}"
    db.init_app(app)
    # db.create_all(app=app)

    from .routes.views import views
    #from .routes.auth import auth

    app.register_blueprint(views, url_prefix='/')
    #app.register_blueprint(auth, url_prefix='/auth')

    from .models import User

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    return app

website/routes/auth.py
# auth.py
from datetime import datetime
from flask import Blueprint, render_template, redirect, url_for, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user
from ..forms import Create_user_form, Login_user_form, Update_password_form, Update_user_form
from ..models import User
from .. import db

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    pass

    # check if user is already logged in

    # form submited

    # check if user actually exists
    # take the user supplied password, hash it, and compare it to the hashed password in database
    # if user doesn't exist or password is wrong, reload the page

    # # if the above check passes, then we know the user has the right credentials

    # return render_template('auth/login.html', form=form)


@auth.route('/sign-up', methods=['GET', 'POST'])
def signup():
    pass

    # check if user is already logged in

    # form submitted

    # check if email is already in our database

    # check if passwords match

    # insert form data

    # add to database

    # return render_template('auth/sign_up.html', form=form)


@login_required
@auth.route('/logout')
def logout():
    flash("Gebruiker uitgelogd")
    logout_user()
    return redirect(url_for('views.home'))


@login_required
@auth.route('/account')
def account():
    # return render_template('auth/account.html', current_user=current_user)
    pass


@login_required
@auth.route('/password-update', methods=['GET', 'POST'])
def update_password():

    # form submited

    # check if passwords match

    # check if password is correct

    # insert data

    # add to database

    # return render_template('auth/password_update.html', form=form, current_user=current_user)
    pass


@login_required
@auth.route('/account-update', methods=['GET', 'POST'])
def update_account():

    # form submitted

    # check if email is already in our database

    # insert data

    # add to database

    # setting form values

    # return render_template('auth/account_update.html', form=form, current_user=current_user)
    pass

website/routes/views.py
from datetime import date, datetime
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import current_user, login_required
from .. import db

views = Blueprint('views', __name__)

###############
# read routes #
###############


@views.route('/')
def home():
    return render_template('home.html')


@views.route('/contact')
def contact():
    return render_template('contact.html')


@views.route('/onze-diensten')
def our_services():
    return render_template('our_services.html')


@views.route('/over-ons')
def about_us():
    return render_template('about_us.html')


#################
# create routes #
#################


#################
# update routes #
#################


#################
# delete routes #
#################

website/templates/about_us.html
<!--inherits from this base -->
{% extends "base/base.html" %}

<!--page specific title -->
{% block title %} over ons {% endblock %}

<!--page specific css -->
{% block stylesheet %} {% endblock %}

<!--page specific content -->
{% block content %}
<!-- component -->
<div class=" text-center min-h-screen bg-white sm:items-center sm:pt-0">
    <br>
    <h1 class="text-4xl sm:text-5xl text-gray-800 font-extrabold tracking-tight">
        over ons.
    </h1>
    <p class="text-normal text-lg sm:text-2xl font-medium text-gray-600 mt-2">
        deze pagina moet nog gemaakt worden.
    </p>
</div>
<!--Footer-->

{% endblock %}

website/templates/base/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/all-icons.css') }}" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />
  <link rel="shortcut icon" href="{{ url_for('static', filename='images/logo.png') }}">
  {% block stylesheet %} {% endblock %}
  <title>gentrit - {% block title %} {% endblock %}</title>
</head>

<body class="bg-white font-sans leading-normal tracking-normal">
  <!--navigation topbar -->
  {% include 'includes/flash_allert.html' %}
  {% include 'includes/header.html' %}
  <!-- page content -->
  <div class="content-container">{% block content %} {% endblock %}</div>

  {% include 'includes/footer.html' %}
</body>

</html>

website/templates/contact.html
<!--inherits from this base -->
{% extends "base/base.html" %}

<!--page specific title -->
{% block title %} contact {% endblock %}

<!--page specific css -->
{% block stylesheet %} {% endblock %}

<!--page specific content -->
{% block content %}
<!-- component -->
<div class="relative flex items-top justify-center min-h-screen bg-white sm:items-center sm:pt-0">
    <div class="max-w-6xl mx-auto sm:px-6 lg:px-8">
        <div class="mt-8 overflow-hidden">
            <div class="grid grid-cols-1 md:grid-cols-2">
                <div class="p-6 mr-2 bg-gray-100 sm:rounded-lg">
                    <h1 class="text-4xl sm:text-5xl text-gray-800 font-extrabold tracking-tight">
                        Vraag of afspraak? neem contact op.
                    </h1>
                    <p class="text-normal text-lg sm:text-2xl font-medium text-gray-600 mt-2">
                        wij zijn op werkdagen altijd tussen <br> 9:00 - 17:00 berijkbaar
                    </p>

                    <div class="flex items-center mt-8 text-gray-600">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                            stroke-width="1.5" viewBox="0 0 24 24" class="w-8 h-8 text-gray-500">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"
                                d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"
                                d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                        </svg>
                        <div class="ml-4 text-md tracking-wide font-semibold w-40">
                            Assen, Straat,
                            Postcode
                        </div>
                    </div>

                    <div class="flex items-center mt-4 text-gray-600">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                            stroke-width="1.5" viewBox="0 0 24 24" class="w-8 h-8 text-gray-500">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"
                                d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                        </svg>
                        <div class="ml-4 text-md tracking-wide font-semibold w-40">
                            +31 1234567890
                        </div>
                    </div>

                    <div class="flex items-center mt-2 text-gray-600">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                            stroke-width="1.5" viewBox="0 0 24 24" class="w-8 h-8 text-gray-500">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"
                                d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                        </svg>
                        <div class="ml-4 text-md tracking-wide font-semibold w-40">
                            info@gb-tech.org
                        </div>
                    </div>
                </div>

                <form method="post" class="p-6 flex flex-col justify-center">
                    <div class="flex flex-col">
                        <label for="name" class="hidden">Volledige naam</label>
                        <input type="name" name="name" id="name" placeholder="Volledige naam"
                            class="w-100 mt-2 py-3 px-3 rounded-lg bg-white  border border-gray-400  text-gray-800 font-semibold focus:border-indigo-500 focus:outline-none">
                    </div>

                    <div class="flex flex-col mt-2">
                        <label for="email" class="hidden">Email</label>
                        <input type="email" name="email" id="email" placeholder="Email"
                            class="w-100 mt-2 py-3 px-3 rounded-lg bg-white  border border-gray-400  text-gray-800 font-semibold focus:border-indigo-500 focus:outline-none">
                    </div>

                    <div class="flex flex-col mt-2">
                        <label for="tel" class="hidden">Nummer</label>
                        <input type="tel" name="tel" id="tel" placeholder="Telefoon nummer"
                            class="w-100 mt-2 py-3 px-3 rounded-lg bg-white  border border-gray-400  text-gray-800 font-semibold focus:border-indigo-500 focus:outline-none">
                    </div>

                    <div class="flex flex-col mt-2">
                        <label for="msg" class="hidden">Bericht</label>
                        <textarea id="message" rows="6"
                            class="w-100 mt-2 py-3 px-3 rounded-lg bg-white  border border-gray-400  text-gray-800 font-semibold focus:border-indigo-500 focus:outline-none"
                            placeholder="schrijf hier uw bericht"></textarea>
                    </div>

                    <button type="submit"
                        class="md:w-32 bg-indigo-600 hover:bg-blue-dark text-white font-bold py-3 px-6 rounded-lg mt-3 hover:bg-indigo-500 transition ease-in-out duration-300">
                        Submit
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/includes/flash_allert.html
<div class="container mx-auto">
    {% for message in get_flashed_messages() %}
    <div class="alert bg-yellow-100 rounded-lg py-2 px-6 mb-3 text-base text-yellow-700 inline-flex items-center w-full alert-dismissible fade show"
        role="alert">
        <strong class="mr-1">FLASH ALERT </strong> {{message}}
        <button type="button"
            class="btn-close box-content w-4 h-4 p-1 ml-auto text-yellow-900 border-none rounded-none opacity-50 focus:shadow-none focus:outline-none focus:opacity-100 hover:text-yellow-900 hover:opacity-75 hover:no-underline"
            data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {%endfor%}
</div>

website/templates/includes/footer.html
<footer class="bg-white">
    <div class="container mx-auto px-8">
        <div class="w-full flex flex-col md:flex-row py-6">
            <div class="flex-1 mb-6 text-black">
                <a href="{{ url_for('views.home') }}" class="flex items-center">
                    <img src="{{ url_for('static', filename='images/logo.png') }}" class="mr-3 h-6 sm:h-9" alt="Logo" />
                    <span class="self-center text-xl font-semibold whitespace-nowrap ">GB - Tech</span>
                </a>

            </div>
            <div class="flex-1">
                <p class="uppercase text-gray-500 md:mb-6">Links</p>
                <ul class="list-reset mb-6">
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-pink-500">FAQ</a>
                    </li>
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="{{ url_for('views.contact') }}"
                            class="no-underline hover:underline text-gray-800 hover:text-pink-500">Help</a>
                    </li>
                </ul>
            </div>
            <div class="flex-1">
                <p class="uppercase text-gray-500 md:mb-6">Wetgeving</p>
                <ul class="list-reset mb-6">
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#"
                            class="no-underline hover:underline text-gray-800 hover:text-pink-500">voorwaarden</a>
                    </li>
                </ul>
            </div>
            <div class="flex-1">
                <p class="uppercase text-gray-500 md:mb-6">Social media</p>
                <ul class="list-reset mb-6">
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-pink-500">Facebook</a>
                    </li>
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-pink-500">Linkedin</a>
                    </li>
                </ul>
            </div>
            <div class="flex-1">
                <p class="uppercase text-gray-500 md:mb-6">Bedrijf</p>
                <ul class="list-reset mb-6">
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="#" class="no-underline hover:underline text-gray-800 hover:text-pink-500">About Us</a>
                    </li>
                    <li class="mt-2 inline-block mr-2 md:block md:mr-0">
                        <a href="{{ url_for('views.contact') }}"
                            class="no-underline hover:underline text-gray-800 hover:text-pink-500">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
        <p class="text-gray-400 m-2">GB -tech © 2021</p>
    </div>

</footer>

website/templates/includes/header.html
<!--Nav-->
<header>
	<nav class="bg-white border border-gray-100 px-4 lg:px-6 py-2.5 ">
		<div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">
			<a href="{{ url_for('views.home') }}" class="flex items-center">
				<img src="{{ url_for('static', filename='images/logo.png') }}" class="mr-3 h-6 sm:h-9" alt="Logo" />
				<span class="self-center text-xl font-semibold whitespace-nowrap ">GB - Tech</span>
			</a>

			<div class="flex items-center lg:order-2">
				<button data-collapse-toggle="mobile-menu-2" type="button" id="mobile-menu-toggle"
					class="inline-flex items-center p-2 ml-1 text-sm text-gray-500 rounded-lg lg:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 "
					aria-controls="mobile-menu-2" aria-expanded="false">
					<span class="sr-only">Open main menu</span>
					<svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
						<path fill-rule="evenodd"
							d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
							clip-rule="evenodd"></path>
					</svg>
					<svg class="hidden w-6 h-6" fill="currentColor" viewBox="0 0 20 20"
						xmlns="http://www.w3.org/2000/svg">
						<path fill-rule="evenodd"
							d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
							clip-rule="evenodd"></path>
					</svg>
				</button>
			</div>

			<div class="hidden justify-between items-left w-full lg:flex lg:w-auto lg:order-1" id="mobile-menu-2">
				<ul class="flex flex-col mt-4 font-medium lg:flex-row lg:space-x-8 lg:mt-0">
					<li>
						<a href="{{ url_for('views.home') }}"
							class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0"
							aria-current="page">Home</a>
					</li>
					<li>
						<a href="{{ url_for('views.about_us') }}"
							class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0 ">Over
							ons</a>
					</li>
					<li>
						<a href="{{ url_for('views.our_services') }}"
							class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0 ">Onze
							diensten</a>
					</li>
					<li>
						<a href="{{ url_for('views.contact') }}"
							class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0">Contact</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
</header>

<script src="{{ url_for('static', filename='js/mobileMenuToggle.js') }}"></script>

website/templates/our_services.html
<!--inherits from this base -->
{% extends "base/base.html" %}

<!--page specific title -->
{% block title %} onze diensten {% endblock %}

<!--page specific css -->
{% block stylesheet %} {% endblock %}

<!--page specific content -->
{% block content %}
<div class=" text-center min-h-screen bg-white sm:items-center sm:pt-0">
    <br>
    <h1 class="text-4xl sm:text-5xl text-gray-800 font-extrabold tracking-tight">
        onze diensten
    </h1>
    <p class="text-normal text-lg sm:text-2xl font-medium text-gray-600 mt-2">
        deze pagina moet nog gemaakt worden.
    </p>
</div>
<!--Footer-->

{% endblock %}